### ISSUE TITLE
Improve support TVs that are always on

### ISSUE THREAD

**Issue by jamjop** [MrAsterisco/homebridge-hisense-tv#18]
The plug-in does not report on/off state to HomeKit therefore I can’t use it for automations. I can really only use it if I know the TVs current power state.

**Comment by jamjop** [comment]
I see this has already been discussed

**Comment by MrAsterisco** [comment]
@jamjop hello and thanks for reporting this! So technically the plugin does report the TV state to HomeKit (it is checked periodically). However, if you have the Home app opened, the status update won't work (I still have to figure out why -- however, I have the same problems with other Homebridge plugins as well).

Would you mind elaborating on what's the issue for you? Maybe there's a solution for it.

**Comment by matthijsf** [comment]
I’m having the same issue on the U7G. The state is always reported as on, likely because of the way the TV handles the OS staying fully operational while the screen is off. If you need me to test something, please do let me know.

**Comment by jparchem** [comment]
I saw a potential solution over on a Home Assistant discussion [HERE](https://community.home-assistant.io/t/hisense-u6g-and-possibly-other-android-tv-control/364853/15).  They were able to ascertain the power state by subscribing to the `/remoteapp/mobile/broadcast/platform_service/data/picturesetting` topic.  If the power state changes, you'll receive a notification message containing a `menu_info` array that contains a list of settings.  Toggling my TV (a model U8G) on and off showed that a particular item in the array, `HDMI Dynamic Range` (menu_id=23) had a menu_flag value of 1 for "OFF" and -1 for "ON".  

<img width="443" alt="menu_value_type int" src="https://user-images.githubusercontent.com/4007519/190319422-9c8fb818-74f6-49f9-bc76-fd1c5fd9ffac.png">

So different models are probably going to have different behavior, but the basics of seeing what gets toggled during a change of power state should still hold true.  

I'm not a TypeScript person, but I would be willing to collaborate with you on this in testing with the model I have.  I'm also not terribly familiar with MQTT, and I'm wondering if the iPhone, iPad, or Mac is off during a change of power state, will it still get the corresponding messages when it comes back online.  I think that would be simple enough for me to test.

**Comment by MrAsterisco** [comment]
That's an awesome insights, thank you for bringing this up @jparchem !

Unfortunately, I don't have the bandwidth to look into this right now: it is quite the change, because it involves subscribing to an additional topic and listening to both at the same time, which (IIRC) isn't something that's supported right now.

In any case, this change will have to be applied to the [Python script](https://github.com/MrAsterisco/hisensetv) first and then implemented in the Homebridge plugin.

**Comment by LeLunZ** [comment]
@jparchem @matthijsf @jamjop if you are still interested:
i could implement the needed changes @jparchem mentioned.
Does someone of you still have the tv and could test them if they are ready?

**Comment by LeLunZ** [comment]
@jamjop  this is now available in the latest version 3.0.0
I am closing this.  So if any problem occurs, please create a new bug report.
