### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by AaronG85** [MrAsterisco/homebridge-hisense-tv#19]
![7A533116-39FB-4F56-93DE-D57F3EA8107E](https://user-images.githubusercontent.com/16955696/132125350-7d32514a-8412-4f8e-b682-d9d32035e58c.png)

Im currently stuck on this step as my windows installation doesn’t have the hisense folder

![25EEB870-5C56-49BC-A009-540C0BD73DB8](https://user-images.githubusercontent.com/16955696/132126646-9776f134-9b3a-4843-b540-ece0577cde47.jpeg)

**Comment by MrAsterisco** [comment]
@AaronG85 I'm so sorry for the delay in getting to this issue, but for some reason GitHub decided to not notify me about it.

By looking at your screenshots, I don't see the `hisense` plugin installed: have you installed it from Homebridge first? Once you have it installed, you should see it in the folder _(assuming that's the right folder, I'm unfortunately not familiar with the Windows setup)_.

Feel free to reopen the issue if the problem isn't solved for you yet.
