### ISSUE TITLE
ModuleNotFoundError: No module named 'paho'

### ISSUE THREAD

**Issue by mensa84** [MrAsterisco/homebridge-hisense-tv#27]
Hello,

I run homebridge on a Debian Linux and it's working fine, but I have a problem with this Hisense plugin.

I did install successfully by "npm -g install homebridge-hisense-tv-remotenow".
Until now, I did not configure anything in homebridge config, cause that very first command for pairing is already failing.
I did only run this:

`root@Server:/usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin# python3.9 hisensetv.py 192.168.1.40 --authorize --ifname ens3
Traceback (most recent call last):
  File "/usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv.py", line 3, in <module>
    from hisensetv import __main__
  File "/usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv/__init__.py", line 12, in <module>
    import paho.mqtt.client as mqtt
ModuleNotFoundError: No module named 'paho'
`

What is the problem?
The TV pairs correctly with the iPhone app and the Linux machine can also connect by telnet to port 36669.
Can you please help me to fix?

**Comment by mensa84** [comment]
I had to install that package:
apt install python3-paho-mqtt

Now I get that error, although my network interface is "ens3", isn't it?

`root@Server:/usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin# python3.9 hisensetv.py 192.168.1.40 --authorize --iframe ens3
usage: hisensetv.py [-h] [--authorize] [--ifname IFNAME] [--get {sources,volume,state}] [--key {power,up,down,left,right,menu,back,exit,ok,volume_up,volume_down,channel_up,channel_down,fast_forward,rewind,stop,play,pause,mute,home,subtitle,netflix,youtube,amazon,0,1,2,3,4,5,6,7,8,9,source_0,source_1,source_2,source_3,source_4,source_5,source_6,source_7}] [--no-ssl] [--certfile CERTFILE] [--keyfile KEYFILE] [-v] hostname
hisensetv.py: error: unrecognized arguments: --iframe ens3`

`root@Server:/usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 02:11:32:2d:27:58 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    inet 192.168.1.7/24 brd 192.168.1.255 scope global dynamic ens3
       valid_lft 76648sec preferred_lft 76648sec
    inet6 fd46:9444:872e:4e94:11:32ff:fe2d:2758/64 scope global dynamic mngtmpaddr
       valid_lft 1751sec preferred_lft 1751sec
    inet6 fe80::11:32ff:fe2d:2758/64 scope link
       valid_lft forever preferred_lft forever
`

**Comment by mensa84** [comment]
That command helped:

`apt install python3-paho-mqtt`

But now I get that errors:

`root@Server:/usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin# python3.9 hisensetv.py 192.168.1.40 --authorize --ifname ens3
[2022-01-16 19:49:27,550] [INFO    ] Unverified SSL context created.
Traceback (most recent call last):
  File "/usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv.py", line 6, in <module>
    __main__.main()
  File "/usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv/__main__.py", line 128, in main
    with tv:
  File "/usr/lib/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv/__init__.py", line 137, in __enter__
    self._mqtt_client.connect(self.hostname, self.port)
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/lib/python3/dist-packages/paho/mqtt/client.py", line 1104, in reconnect
    sock.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)
`

**Comment by MrAsterisco** [comment]
Thanks for reporting this! This command is already in the Readme, it's just using `pip` instead of `apt`, to make it more distribution-generic.

**Comment by mensa84** [comment]
> Thanks for reporting this! This command is already in the Readme, it's just using `pip` instead of `apt`, to make it more distribution-generic.

I know, but I jumped over that step cause before the Readme is saying "If you're using Hoobs, ...".

**Comment by MrAsterisco** [comment]
Ha, good point! Let me change that.
