### ISSUE TITLE
README Needs Updated Instructions or Simpler Steps

### ISSUE THREAD

**Issue by mitch7391** [MrAsterisco/homebridge-hisense-tv#33]
**Describe Your Problem:**
I thought I would try migrate from my Hisense repo over to yours seen as my installation steps are quite complicated and after hours I still cannot get through your installation steps; and I do not feel like I am new to all this stuff. I am on the official RPi image which it seems is a more difficult distro to use based on your closed issues. I think the README needs updating as a new user should not have to navigate that, several closed issues and links to tool installation guides. I still cannot get 'paho' to be happy after following all the instructions, google guides, etc. Not really after support, just frustrated and going to stay on my repo sorry; but thought I would let you know there might need to be some work done here; I hope this does not read as rude.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by MrAsterisco** [comment]
@mitch7391 Thank you for reporting this. I can definitely relate to what you're saying: there are a lot of open source projects that seem to fix you problem or address your issue, but then they don't or they're hard to configure.

I, however, follow the culture of "if you have a problem, search for a solution", so I don't like complaining for the sake of doing just that. 

This plugin was built based on what I have: my HiSense TV and a Homebridge instance running on Ubuntu. For that configuration, the README works perfectly. I do understand that other people may have different TVs and different operating systems, but I have to rely on those people to open pull requests that update and improve the documentation, as I cannot do it myself (I cannot test any of those configurations). I tried to update the README as output of all the issues we solved in the past, but once again: I rely on what was said in those issue, I do not have a way to test if they're right.

I do not see a next step from your issue and I feel like this is not a good way to begin a conversation. I understand you're frustrated, but please remember we're all doing this in our free time and I am not in any way connected to HiSense, meaning that I'd have to buy all the HiSense TVs in the world to write a complete README. Unfortunately, that is outside of my time and financial possibilities.

I'd kindly ask you to elaborate more on the problems you're having or, even better, open a PR that makes the changes you'd like to see to the README. For the time being, I'll close this issue: feel free to reopen if you have an actionable item or additional actionable suggestions.

Once again, thank you for checking out this plugin and I am truly sorry it doesn't work out of the box for you.

**Comment by mitch7391** [comment]
@MrAsterisco I will admit I was terribly frustrated when I wrote this, but my intent was not to offend; so I apologise for that.

> I, however, follow the culture of "if you have a problem, search for a solution", so I don't like complaining for the sake of doing just that. 

As I said, I spent much time reading your README and closed issues with similar problems; I went to the links you shared and spent a fair bit of time googling the issue myself. All of which would tell me python 3 and paho-mqtt where installed correctly and every time I ran the python script it would tell me paho was not recognised. I am not new to figuring out unusual solutions (as you may remember I have my own strange solution to running my Hisense TV); but after so much time wasted for what I though might be close to a 'out of the box solution', there was no point pursuing something I had working in my own round about way.

> I do not see a next step from your issue and I feel like this is not a good way to begin a conversation. I understand you're frustrated, but please remember we're all doing this in our free time and I am not in any way connected to HiSense, meaning that I'd have to buy all the HiSense TVs in the world to write a complete README. Unfortunately, that is outside of my time and financial possibilities.

I understand as I run my own work that other people use and have had to adapt to some of their different systems that I do not use. I am not in the habit of writing GitHub issues to complain without logs or errors, but this just took up too much of my time, I do not have the time to work on it and and create a PR; I thought I would let you know that you may need to revise your instructions for other users. Again, sorry for any offence caused as that was not my intention.

**Comment by MrAsterisco** [comment]
> but my intent was not to offend; so I apologise for that.

None taken, don't worry! 😊 

> All of which would tell me python 3 and paho-mqtt where installed correctly and every time I ran the python script it would tell me paho was not recognised.

To me, that looks like a configuration issue on your system, rather than an issue with the script or with the README. I also had problems in the past with other Python libraries. Python is an annoying language for this kind of stuff: just randomly asking questions here... But have you checked which interpreter is the default one (2.7 or 3.x)? I also found [this webpage](https://forums.raspberrypi.com/viewtopic.php?t=216114) that seems to be pointing to a similar issue.

> but this just took up too much of my time

Once again, I am truly sorry. We're all using our free time here and I know it can be annoying to waste your spare time.

> I thought I would let you know that you may need to revise your instructions for other users.

This is the part that I find a bit weird in your comment: if you have ideas on how to revise the README, you should push them forward. If you don't have suggestions, I'm not sure how I can improve and then I don't see an actionable item from this. 

I am sure my README isn't perfect (and it'll probably never be), but I also don't know how to make it better, if people don't tell me what to improve. I'm all for making it better, but I need constructive feedback to do so.

As an actionable output of this conversation, I saw two things that I could do, so I updated the README to:
1. Include a disclaimer that explains my configuration and warns users with different configuration that this plugin may not work immediately out-of-the-box. Also, I asked people to open issues and PRs if they find different steps or mistakes.
2. Mention how to get the network interface name on macOS, as output of #32 .

To end, I can only apologize that this plugin doesn't fit your needs and I can also say that I'm not happy that you won't be pursuing the right configuration anymore, as it would've definitely helped somebody else to have your resolution steps described somewhere. But, I guess that's just how open source goes 😊 

Enjoy the rest of your evening!

**Comment by mitch7391** [comment]
> To me, that looks like a configuration issue on your system, rather than an issue with the script or with the README.

It would not be the first time someone has told me that the official Homebridge image (accidentally called this the official RPi image earlier) is a bit of a basic and 'broken' one; which is a shame as I imagine a lot of users would user it.

> But have you checked which interpreter is the default one (2.7 or 3.x)? I also found this webpage that seems to be pointing to a similar issue.

Yep 3.x and followed a guide you linked to make sure it is. I did look at this link you attached right now and tried every solution suggested amongst the closed issues on the topic as well as quite a few googled.

> This is the part that I find a bit weird in your comment: if you have ideas on how to revise the README, you should push them forward. If you don't have suggestions, I'm not sure how I can improve and then I don't see an actionable item from this.

Sorry, the intent was not to leave you hanging and tell you something was bad. If I had found a solution for my problem, then I would have provided a solution for how you could add extra steps that may be needed for people with the same issues on this distro. As you said, it is more an issue with the distro, but people using it may need extra steps to install your plug-in; which then does fall down to info needed here. Again, if I had that info and solution I would be happy to provide it for you, but I could not work it out.

> To end, I can only apologize that this plugin doesn't fit your needs and I can also say that I'm not happy that you won't be pursuing the right configuration anymore, as it would've definitely helped somebody else to have your resolution steps described somewhere. But, I guess that's just how open source goes 😊

I would probably be more hard pressed to make it work if I did not already have my own solution; I just wanted to give yours a  go as it is a proper plug-in and mine is not. I tried again for the last hour and still am not having a win; perhaps I will try again in the future but as I said I have sunk a lot of time into this I should have been putting into my own work. 

It is not your fault, so no need to be sorry, I think like you said that maybe a warning in the README might go some distance. Thanks and have a good night too.
