### ISSUE TITLE
An error occurred while fetching inputs: TypeError: Cannot read properties of null (reading 'join')

### ISSUE THREAD

**Issue by mensa84** [MrAsterisco/homebridge-hisense-tv#34]
Hello,

my homebridge log is full with that error:

`An error occurred while fetching inputs: TypeError: Cannot read properties of null (reading 'join')`

How to fix that?

**Comment by MrAsterisco** [comment]
@mensa84 Hello and thanks for reporting this! This error usually indicates that there is something wrong with the configuration of your TV. Are you able to perform actions on your TV and see the state via Home?

**Comment by mensa84** [comment]
I see the correct state, but turning off or on does not work.
I am on Debian Linux. Must i install netifaces for newest release? Cause apt install netifaces does not work.

**Comment by mensa84** [comment]
RemoteNow App from Hisense works without problems.

**Comment by MrAsterisco** [comment]
The newest release needs `netifaces`, yes: on Debian it should be available in the default repo:

```
apt install python3-netifaces
```

If you're unable to control the state of the TV, I can assume something is wrong in the configuration. Are you able to send command using the Python script directly?

**Comment by mensa84** [comment]
You are right, thanks! The command line scripts also did not work anymore cause due to the update the ssl files were deleted from `/usr/lib/node_modules/homebridge-hisense-tv-remotenow/`.
Is this normal behavior? Where do you suggest to store that ssl files to not get deleted by an update?

**Comment by MrAsterisco** [comment]
@mensa84 unfortunately, yes, but it's out of our hands. When `npm` (the package manager that Homebridge uses to install plugins) finds a new version, the entire folder is deleted and replaced with the version that's on the repo.

You can put your certificates anywhere else, outside of the `/usr/lib/node_modules` folder. The important thing is that wherever you move them, they are still readable from the Homebridge user.

I'll add this to the README file.

**Comment by mensa84** [comment]
I have created following subfolder in the homebridge directory:

`/var/lib/homebridge/hisense-ssl`

Do you think this is a good idea and will survive all updates?

**Comment by MrAsterisco** [comment]
Is `/var/lib/homebridge` the folder where also the `config.json` file of Homebridge is? In that case, yes.

**Comment by mensa84** [comment]
Yes, it is that folder.

**Comment by MrAsterisco** [comment]
Then it should be fine, because updates of Homebridge usually don't override the `config.json`.
