### ISSUE TITLE
Finding Network Interface Name in Windows

### ISSUE THREAD

**Issue by adamjthompson** [MrAsterisco/homebridge-hisense-tv#37]
How do you find the network interface name in Windows? I'm stuck on that step during my installation.

Thanks!

**Comment by MrAsterisco** [comment]
Hey @adamjthompson ! Thanks for opening this issue.

I am not familiar with Windows and I have never tested this plugin on this platform, so you may experience additional problems. In theory, Python is cross-platform and with the changes introduced in version 2, everything should be supported, but... be aware.

I quickly looked up on Google and I found this [question on SuperUser](https://superuser.com/questions/358766/get-active-network-interface-on-windows), where they report this command:

```powershell
netsh interface show interface
```

Please let me know if this works for you: if it does, I'll update the README to include instructions for Windows as well.

**Comment by adamjthompson** [comment]
@MrAsterisco Thanks! I had been unsuccessful in my Googling attempts thus far. ;-)

That command resulted in two "Interface Name" entries: "Local Area Connection" and "Ethernet". I am not sure how to use an ifname with multiple words, but using "Ethernet" (no quotes) resulted only in the following error messages:

[2022-02-04 11:40:02,982] [INFO    ] Unverified SSL context created.
Traceback (most recent call last):
  File "C:\Users\xbox\AppData\Roaming\npm\node_modules\homebridge-hisense-tv-remotenow\bin\hisensetv\__init__.py", line 61, in get_mac_address
    interface = netifaces.ifaddresses(ifname)
ValueError: You must specify a valid interface name.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XXXXXX\AppData\Roaming\npm\node_modules\homebridge-hisense-tv-remotenow\bin\hisensetv.py", line 6, in <module>
    __main__.main()
  File "C:\Users\XXXXXX\AppData\Roaming\npm\node_modules\homebridge-hisense-tv-remotenow\bin\hisensetv\__main__.py", line 125, in main
    tv = HisenseTv(
  File "C:\Users\XXXXXX\AppData\Roaming\npm\node_modules\homebridge-hisense-tv-remotenow\bin\hisensetv\__init__.py", line 116, in __init__
    self._mac = get_mac_address(network_interface)
  File "C:\Users\XXXXXX\AppData\Roaming\npm\node_modules\homebridge-hisense-tv-remotenow\bin\hisensetv\__init__.py", line 64, in get_mac_address
    raise HisenseTvError("Unknown network interface: " + ifname)
hisensetv.HisenseTvError: Unknown network interface: Ethernet

**Comment by MrAsterisco** [comment]
@adamjthompson Thanks for your detailed response!

> I am not sure how to use an ifname with multiple words

Assuming the shell you're using is POSIX compliant (if you're on Windows 10/11, both the Windows Terminal or the new Powershell are), to pass parameters with spaces you can either use `"` (double quotes) or `\ ` (backslash space).

> resulted only in the following error messages

I'm assuming this means that the result of that command is not what we're looking for then, so maybe you were right and it's not so easy to find it on Google.

The easiest way would be to run a Python shell on your system (you should be able to do so by running `python` or `python3` without any parameters) and then typing:

```python
import netifaces
```

press Enter and then:

```python
netifaces.interfaces()
```

This should give you an output that looks like this (even though the names you see below are from macOS):

```python
['lo0', 'gif0', 'stf0', 'anpi0', 'anpi1', 'en0', 'en4', 'en5', 'en2', 'en3', 'ap1', 'en1', 'utun0', 'utun1', 'utun2', 'bridge0', 'awdl0', 'llw0', 'utun3', 'utun10']
```

Then, to identify which interface your computer is actually using, you can run the following command trying all the values you got from the array above:

```python
netifaces.ifaddresses('interface-name-here')
```

This command will return all the IP Addresses that are configured for that interface. I'm assuming you can recognise the IP of your LAN, but in case you don't remember it, you can also look in the Windows Settings or on your router config page.
An example output looks like this:

```python
{2: [{'addr': '10.0.1.30', 'netmask': '255.255.255.0', 'broadcast': '10.0.1.255'}]}
```

(In this case, my computer's IP is `10.0.1.30`).

When you found the right one, you just need to pass that interface name to the script.

> An error occurred while fetching inputs: TypeError: Cannot read properties of null (reading 'join')

Yes, indeed: this error appears when the script is unable to connect and hence we're unable to retrieve the list of sources of the TV.

> Even with this error and the inability to connect to the TV using the Python command, it DOES show up in HomeKit and I AM able to see and control the power on/off status, which is the main functionality I wanted.

Yeah, that part will work anyway, but please be aware that the power state is not always correctly displayed in HomeKit. Also, you will be able to turn on the TV, but not turn it off, nor control it via the iOS remote.

I'd suggest, if you have a bit of time, to run the steps above and configure the plugin properly, as you can the also use the TV in your Home scenes or to trigger other accessories.
Also, other people running this plugin on Windows will thank you! 🤓

**Comment by adamjthompson** [comment]
Using netifaces returned three interface names, all formatted like this: {00000000-0000-0000-0000-000000000000}.

I tried all three with "ifaddresses", but they all generated the same error:

```
File "<stdin>", line 1
    netifaces.ifaddresses({00000000-0000-0000-0000-000000000000})
                                                 ^
SyntaxError: invalid decimal literal
```
From my googling, it sounds as if it's because a variable name cannot begin with a number, but I know nothing about Python,  so that doesn't help me solve the issue. I hope it helps you, perhaps?

Thanks again for trying to troubleshoot this with me!

**Comment by adamjthompson** [comment]
Wow! I THINK I have it working correctly now!

Based on one of your other posts ( #26 ), I deduced that the permissions of the service were the issue. I changed the Windows "Log On As" settings for the Homebridge Service from "Local System Account" to my logged in user account. After restarting the service, the plugin grabbed all of the inputs and no longer generates errors. One input came through as "Unknown", so I had to rename it manually. I'm hoping/assuming it won't cause any issues.

I'll let you know if I run into anything else, but adding details to the README on how to obtain the network interface name and how to change the windows service account will help other Windows user like myself.

**Comment by MrAsterisco** [comment]
> I changed the Windows "Log On As" settings for the Homebridge Service from "Local System Account" to my logged in user account.

Could you elaborate on how you did that? Or better, if you have time, could open a PR changing the Readme file with the instructions for Windows?

> Today, I noticed that the TV no longer shows the inputs in the Home app.

This has been raised multiple times, but unfortunately it's a known issue. You can find the list of known issues [here](https://github.com/MrAsterisco/homebridge-hisense-tv#known-issues). Generally, there is no need to remove it and add it again, just force quitting Home and reopening does the trick.

> Additionally, I notice that I am unable to switch inputs, or do anything other than control the power on/off, but at least I can see which input is active.

Looks like your TV works differently than mine, then. Could you try to run the same commands using the Python script directly and post your output?

```bash
# This one should work.
python3 hisensetv.py --get sources <TV_IP_Address_Here> --ifname <Interface_Name_Here>
# This one should return an error.
python3 hisensetv.py --key source_<One_Source_Name_Here> --ifname <Interface_Name_Here>
```

_Please, replace the <> variables with the actual values for your configuration._

**Comment by adamjthompson** [comment]
@MrAsterisco 

I can do a PR for the readme file.

Here is the output of running those two commands (MAC Addresses removed):

### First Command
```

[2022-02-07 15:17:16,710] [INFO    ] Unverified SSL context created.
[2022-02-07 15:17:16,715] [INFO    ] Network interface MAC Address: xx:xx:xx:xx:xx:xx
[
    {
        "displayname": "Channels",
        "is_signal": "1",
        "sourceid": "1",
        "sourcename": "Tuner"
    },
    {
        "displayname": "PlayStation",
        "is_signal": "0",
        "sourceid": "3",
        "sourcename": "HDMI 2"
    },
    {
        "displayname": "Roku",
        "is_signal": "0",
        "sourceid": "4",
        "sourcename": "HDMI 1"
    }
]
```
### Second Command
```
[2022-02-07 15:25:19,752] [INFO    ] Unverified SSL context created.
[2022-02-07 15:25:19,756] [INFO    ] Network interface MAC Address: xx:xx:xx:xx:xx:xx
[2022-02-07 15:25:19,850] [INFO    ] sending keypress: source_4
```
No errors were generated, but nothing happened on the TV either. I was not able to use a source "name" as you indicated, but I assume the source numbers work the same way.

I have one other input, HDMI 3, which always displays as "Unknown" in HomeKit (I assume it is sourceid 2?). I have to rename it to Xbox, but it loses that name when the inputs disappear from the app. After force-quitting the app and reloading it, it appears again with the name "Unknown" unless I remove it from HomeKit and re-add it (since that is the only time I can name the input).

**Comment by adamjthompson** [comment]
Actually, I'm very new to GitHub and have no idea how to send a PR! 😂

**Comment by MrAsterisco** [comment]
> No errors were generated, but nothing happened on the TV either. I was not able to use a source "name" as you indicated, but I assume the source numbers work the same way.

Unfortunately, this confirms that your TV is incompatible with the Python script. The command we're sending it's ignored by the TV, not much we can do. You can use [MQTT Explorer](http://mqtt-explorer.com/) to sniff whatever command is being sent to the TV: once you have that, we can attempt to add support by providing some kind of "mode" to the Python script that controls how commands are sent, but that's a "future us" problem. Could you open an issue on the [Python script repo](https://github.com/MrAsterisco/hisensetv) with your TV model and, if you can, the information you got from MQTT Explorer?

> I have one other input, HDMI 3, which always displays as "Unknown" in HomeKit

I feel like this "Unknown" input is rather a bug in the script than your missing HDMI 3. I'm saying this because the output of the `--get sources` only shows 3 inputs ("Channels", "PlayStation", "Roku") and there is no reference to the "Xbox" input.

> Additionally, triggering events based on the power state of the TV seems inconsistent right now.

I do not have this issue here, but also my TV is very different than yours: I have an automation that runs when I turn off the TV (with some additional conditions) and it runs almost flawlessly. "Almost" because it takes a few seconds for HomeKit to realize that the TV changed state. This is because of how the TV State is fetched: because the TV doesn't emit any event when turned on or off, we have to periodically try to connect and update HomeKit. IIRC, this currently happens every 10 seconds, meaning that, in the worst case, you'll have a 10 seconds delay after turning on/off the TV.

**Comment by adamjthompson** [comment]
@MrAsterisco 

I am not a developer and, sadly, have zero knowledge of MQTT. I downloaded and installed Mosquitto and MQTT Explorer but have no idea how to use it yet. If you have any ideas on what to try or where to look for help, please let me know. I am happy to help you troubleshoot in any way that I can. 

It looks like I need to subscribe to a "topic" in order to analyze traffic, but I may be completely misunderstanding how this is all supposed to work and I have no idea yet how to proceed from here. Please pardon my ignorance. ☺️

**Comment by MrAsterisco** [comment]
@adamjthompson first of all: don't worry! In my mother tongue we say "nobody is born self-thought": there's absolutely nothing to be sorry about.

So, MQTT Explorer will show you a window with some connection settings at startup. You'll have to input the same settings that you used for the Homebridge plugin (so same IP address, same SSL mode and so on). This screenshot from #30 should help you:

![149905658-2172c470-739c-4bd3-ad18-27ba6e53b2ab](https://user-images.githubusercontent.com/863842/153159690-3d19e518-93fe-45ea-968d-0d46141efb4d.png)

Once you're connected, you should start using the RemoteNOW app to control your TV. You'll see a lot of messages coming and going: the one you're interested in is the one triggered when changing source on the RemoteNOW app. You can also send a screenshot of what you see in the MQTT Explorer window after changing source and we can start from there.

With some patience, I'm sure we can sort something out!

**Comment by adamjthompson** [comment]
I appreciate your kindness.

So far, I have been unsuccessful with ever getting the RemoteNow app to work with my TV, even though it IS listed as being compatible. I tried a hard reset today (unplugging the TV), and the app still cannot see my TV on my network. SO, it looks as if MQTT Explorer will not do me any good until I am able to somehow get that working.

If I CAN get it working, I will try connecting to it using MQTT Explorer. What username and password should I use? Is what is shown in the image correct?

**Comment by adamjthompson** [comment]
I will try connecting using WiFi, which I have not yet tried. After I have successfully added the TV, am I able to switch it back to Ethernet?

**Comment by MrAsterisco** [comment]
@adamjthompson yeah, that doesn't sound good. Have you tried reaching out to Hisense customer service to see if they are aware of incompatibilities between your TV model and RemoteNOW?

Could you also post the TV model number here, so we can add it as currently unsupported in the README?

**Comment by MrAsterisco** [comment]
Thanks! I updated the README to list this model as incompatible. If you're okay with this, I'd then close this issue, as there's unfortunately not much we can do. Feel free to reopen it, if you manage to get a hold of Hisense customer service.
