### ISSUE TITLE
hisensetv.py

### ISSUE THREAD

**Issue by kowmen** [MrAsterisco/homebridge-hisense-tv#40]
Hi im using Hoobs latest update, but on RPI box,
I install all what i must from your manual. 
But i dont know how to run hisensetv.py script to get code from tv. I tried everything but nothing works. Can you help me?

**Comment by MrAsterisco** [comment]
Hi @kowmen !

I'm happy to help, but I'll need a bit more details on where you get stuck trying to run the Python script. Do you have SSH/Shell access to the machine?

**Comment by kowmen** [comment]
Hi i used this path to run a script 

/var/lib/hoobs/hisensetvremotenowbridge/node_modules/homebridge-hisense-tv-remotenow/bin python3.8 hisensetv.py <192.168.1.216> --authorize --hoobs <Hisense58>
and this is answer
bash: syntax error near unexpected token `newline'
I have some mistake in authorize ( i dont know what ifname means ) i used name from router where i have named rpi as hoobs. Im loged to hoobs from macbook.

**Comment by MrAsterisco** [comment]
Thanks for posting this. I have a few questions: first of all, why are you passing a `--hoobs` parameter to the script? There is no such parameter. Also, what version of Python are you running?

**Comment by kowmen** [comment]
Hi i try this a used ip a from my homebridge device ( i switched from hoobs to homebridge cause its better ), this is flags=4163<UP,BROADCAST,RUNNING,MULTICAST> from my hmebridge RPI, im so confused what is ifname? 

/var/lib/homebridge/node_modules/homebridge-hisense-tv-remotenow/bin python3.8 hisensetv.py <192.168.1.216> --authorize — THIS IS FOR ME UNKNOW PARAMETER TO FILL :D

I used python 3,9. Its problem with this?

**Comment by MrAsterisco** [comment]
You changed your setup, so I'd assume the previous error won't apply to you anymore.

To find your network interface name, please follow [the instructions](https://github.com/MrAsterisco/homebridge-hisense-tv#generic-linux) of the TV setup. :) 

I'll go ahead and close this issue for now. Feel free to open a new one if you encounter other issues.
