### ISSUE TITLE
Cannot run hisensetv.py

### ISSUE THREAD

**Issue by Hawkceister** [MrAsterisco/homebridge-hisense-tv#41]
**Describe Your Problem:**
Hello !

I have a problem for running the python script hisensetv.py, to pairing the TV. I'm running home bridge on Raspberry pi. Trying different ssl mode. Disable mode allow me to turn the TV off. 

The PIN code do not display on the TV

When I run the command :

```pi@homebridge:/usr/local/lib/node_modules/homebridge-hisense-tv-remotenow/bin $ python3.9 hisensetv.py 192.168.1.XX --authorize --ifname eth0```

**Logs:**

```
[2023-01-14 10:43:24,305] [INFO    ] Unverified SSL context created.
[2023-01-14 10:43:24,307] [INFO    ] Network interface MAC Address: b8:27:eb:73:a5:9f
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv.py", line 6, in <module>
    __main__.main()
  File "/usr/local/lib/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv/__main__.py", line 128, in main
    with tv:
  File "/usr/local/lib/node_modules/homebridge-hisense-tv-remotenow/bin/hisensetv/__init__.py", line 136, in __enter__
    self._mqtt_client.connect(self.hostname, self.port)
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1073, in reconnect
    sock.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Plugin Config:**
```
{
            "ifname": "eth0",
            "devices": [
                {
                    "id": "HiSenseTV",
                    "name": "Hisense TV",
                    "ipaddress": "192.168.1.XX",
                    "macaddress": "40:CD:7A:XX:XX:XX",
                    "sslmode": "default"
                }
            ],
            "platform": "HiSenseTV"
        }
```
**Screenshots:**

**Environment:**

* **Plugin Version**: 2.0.0
* **Homebridge Version**: 1.6.0
* **Node.js Version**: 18.13.0
* **NPM Version**: 
* **Operating System**: Raspbian

**Comment by MrAsterisco** [comment]
Hey @Hawkceister ! Thanks for reaching out.
Based on this line of your log:

> ConnectionResetError: [Errno 104] Connection reset by peer

It looks like your TV is either:
- Not listening for connections
- Using a different SSL certificate that we don't support.

Does your TV work with the RemoteNOW app?

**Comment by Hawkceister** [comment]
Yes it work with RemoteNow app :/

**Comment by MrAsterisco** [comment]
I would then say your TV is unfortunately not supported. You are welcome to fork the repo and look more into it: if you find a solution, I'm happy to accept it into the main repo and release an update 😊 

Unfortunately, I cannot help you further, as I don't know how to _sniff_ the SSL certificates that your TV is using. I have no experience with that and the supported SSL certificates were taken from another repo.

Would you mind giving me your TV model, so I can add it to the unsupported list?

**Comment by LeLunZ** [comment]
@Hawkceister the app got an update where something with python>3.8 got fixed.
You can also try the certs here: https://github.com/d3nd3/Hisense-mqtt-keyfiles

Which TV model do you have?

**Comment by LeLunZ** [comment]
@Hawkceister the new version 3.0.0 doesnt use the provided python tool anymore but scripts bundled with the application. They are now automatically installed.

I am closing this.  So if any problem occurs, please create a new bug report.
