### ISSUE TITLE
setup code is missing in log 

### ISSUE THREAD

**Issue by alan2022000** [MrAsterisco/homebridge-hisense-tv#46]
hi i have managed to setup my hisense tv on hoobs running on a pi4
hoobs has the tv listed and if i click on it in the hoobs website it does turn my tv on or off so i can confirm the plugin is communicating with it. 

the prpoblem i have is the log is not showing the setup code. my iphone is showing the tv to add when i try to add it to home app. is there another way to get the code. or am i looking in the wrong log?

heres the log from hoobs when it boots up

19/04/2023, 00:24:09hub is running on port 80
19/04/2023, 00:24:10Tuya Platform Bridge starting
19/04/2023, 00:24:11Hisense Tv Bridge starting
19/04/2023, 00:24:14Hisense Tv BridgeLoaded plugin 'homebridge-hisense-tv-remotenow'
19/04/2023, 00:24:14Hisense Tv BridgeLoading 1 platforms...
19/04/2023, 00:24:14Hisense Tv BridgeHiSenseTVAdding new accessory: HiSense
19/04/2023, 00:24:14Hisense Tv BridgeHiSense 24C8 is running on port 42947.
19/04/2023, 00:24:14Hisense Tv BridgeBridge is running on port 51836.
19/04/2023, 00:24:14Tuya Platform BridgeLoaded plugin 'homebridge-tuya-platform'
19/04/2023, 00:24:14Tuya Platform BridgeLoading 1 platforms...
19/04/2023, 00:24:14Tuya Platform BridgeBridge is running on port 51826.

i hope you can help me fimd the code as im this step away from asaying hey siri turn the tv on.

thanks
alan

**Comment by MrAsterisco** [comment]
Hey @alan2022000 !

If I remember correctly, the code shows up in the Homebridge home page. If you navigate to your Homebridge IP address and log into the UI, you should be able to retrieve the code.

**Comment by alan2022000** [comment]
Thanks for that. Still wasn't any code. But I did get it to work this morning. I thought I'd try the code you use when adding a new bridge to the home app. That code is always the same. And it worked. It said in the instructions that each time you add a TV the code will be different. I think that bit is what thrown me off. I guess on hoobs the code doesn't change for anything that needs a setup code. All working now. I like being able to say hey siri turn the TV off. Saves looking for the remote now. On 19 Apr 2023 8:15 am, Alessio Moiso ***@***.***> wrote:
Hey @alan2022000 !
If I remember correctly, the code shows up in the Homebridge home page. If you navigate to your Homebridge IP address and log into the UI, you should be able to retrieve the code.

**Comment by MrAsterisco** [comment]
Oh that's very interesting! I'll leave this issue open until I have to update the README. Thanks for reporting this!

**Comment by alan2022000** [comment]
if it helps with your instructions and others i have listed below what commands i had to do differently to have it work on a pi4 running hoobs - original first lind then what i did instead below

sudo su - homebridge
sudo su

sudo apt-get install python3-dev
i ran this one but on pi, 3.7 is the latest for some reason. not 3.8.

on Linux, it is located in /usr/local/lib/node_module/homebridge-hisense-tv/bin
on pi with hoobs its here instead - im guessing the random numbers bit can change so might be different for others
also i use "find . -name "hisense*" -type d" from root to find where it was and this was the only result
/usr/local/share/.cache/yarn/v6/npm-homebridge-hisense-tv-remotenow-2.0.0-f3ea47064066d2fc124d49803de3e2d92b3bedb5-integrity/node_modules/homebridge-hisense-tv-remotenow/bin/


python3.8 hisensetv.py <TV_IP_ADDRESS> --authorize --ifname <NETWORK_INTERFACE_NAME>
python3.7 hisensetv.py 192.168.0.150 --authorize --ifname wlan0
if i dont chnage it from 3.8 to 3.7 it errors out as the pi only has 3.7 as its latest not 3.8.

then finally as above in this thread. the log doesnt show a code but you just use the same code as you would when adding the bridge. 
ive installed hoobs a few times on different pi's and the code is always the same... its 03145154


hope this helps.

**Comment by LeLunZ** [comment]
I think the issue here is that the plugin actually configures a new bridge.
Which can be easily misunderstood, as other plugins don't do that.

@alan2022000 does your issue still exists (will close this issue if not)

**Comment by LeLunZ** [comment]
Just found out its normal that the setup code is the same as the one shown below the qr code.
You can also scan the normal homebridge qr code and it will suggest you add the new tv.
